
version: "3"
services:
  api-nestjs:
      build:
        context: .
        dockerfile: Dockerfile
        target: dev
      env_file:
        - .env
      ports:
        - "3000:3000"
      volumes:
        - /src:/app/src
      depends_on:
        - postgres
      networks:
        - postgres
  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
 
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
 
  
 
networks:
  postgres:
    driver: bridge